function [rand_track,original_ratio,Rdna,Rgrad,cnt_foci] = randomize_track3(foci_track,dna_track,mask_track,varargin)
% [rand_track,original_ratio,Rdna,Rgrad,cnt_foci] = randomize_track3(foci_track,dna_track,mask_track,varargin)
% TRY HERE WITH A PROBABILITY APPROACH BASED ON XRAY SIMULATION RESULTS
% PROBA TO HAVE A FOCUS IS SIMPLY THE NUMBER OF FOCUS DIVIDED BY THE SUM OF
% DNA SIGNAL ALONG TRACK. THEN USE THAT PROBA TIMES THE DNA SIGNAL ALONG
% TRACK AND COMPARE THIS TO A RANDOM VALUE.
% Input:
% foci_track is a vector made of 0, except for position of focus center
% where the value is set to the intensity of the peak.
% dna_track is a vector of the DAPI intensity along track. Used as a
% weighting factor for randomizing spot position
% mask_track is a vector of the mask to use to compute Rdna and Rgrad.
% Usually this mask is smaller than the edges of DNA to avoid large
% gradient values at the edge of the nucleus.
%
% Output:
% rand_track is the same vector length with foci center position
% randomized.
% original_ratio: Rdna and Rgrad from given image
% Rdna is the Rdna along the random track (mean,std)
% Rgrad is the Rgrad along the random track (mean,std)
% cnt_foci is a 1x2 array with first value the original number of foci in the 
% track and the 2nd value the average number of foci generated by random process.
% Both number should be close
%
% Options:
% 'size': Default is set to 2, and can be modified. This is the sigma value
% used to simulate the focus shape using a gaussian filter. Then a local
% minima approach is used to detect the position of the peak.
%
% 'iteration': Default is 1. Number of randomization along the track. If
% more than 1, then rand_track and rand_gauss will be arrays, whose number
% of columns will be the lenght of foci_track and each row will represent
% one randomization.
%
% 'max_depth': Default is 0.1. NOT AN OPTION ANYMORE. SINCE WE ONLY HAVE
% PEAKS TO RANDOMIZE, FAULT TO DETECT SHOULD ONLY HAPPEN WHEN TWO RANDOM
% EVENTS ARE LEADING TO A SINGLE PEAK. SO SET THIS TO VERY LOW TO MAKE SURE
% WE DONT MISSS ANY PEAK.
% 'max_size': Default is 2. Parameter used for local minima.
%
% 'min_dist': Default is 1. During randomization, minimum pixel distance
% between peak, befor running the gaussian.
%
% Example
% rand_track = randomize_track3(foci_track,dna_track,mask_track,'iteration',5,'size',2)

%
% Sylvain Costes, LBNL, August 2005
% Modified from randomize_track2 on SEPT 2006
%
% See randomize_track for a simpler alternative

% default values
sigma = 2;
iteration = 1;
max_depth = 0.01;%DO NOT CHANGE!!!
max_size = 2;
min_dist = 1;

% Compute gradient and turn all arrays to double
track_grad = abs(gradient(dip_image(dna_track))); % this works only in dipimage. In matlab, different
track_grad = double(track_grad)';
dna_track = double(dna_track);
foci_track = double(foci_track)>0;
mask_track = double(mask_track)>0;
original_ratio(1) = mean(dna_track(foci_track))/mean(dna_track(mask_track>0));
original_ratio(2) = mean(track_grad(foci_track))/mean(track_grad(mask_track>0));
fprintf('Rdna = %5.2f and Rgrad = %5.2f before randomization\n',original_ratio(1),original_ratio(2));

for i=1:2:length(varargin)
    if (~isstr(varargin{i}))
        fprintf('Property #%d is not a string\n',round(i/2));
        return;
    end
    switch(varargin{i})
        case 'size'
            sigma = varargin{i+1};
        case 'iteration'
            iteration = varargin{i+1};
        case 'max_size'
            max_size = varargin{i+1};
        case 'min_dist'
            min_dist = varargin{i+1};
    end
end

% In case tracks were made much larger than nucleus width, force randomization
% only between first and last focus along track.
index_edge = find(foci_track > 0);
if length(index_edge) == 1
    rand_track = repmat(foci_track,[iteration,1]);
    rand_gauss = rand_track;
    Rdna = [];
    Rgrad = [];
    cnt_foci = [];
    fprintf('Only one focus for this track\n');
else
    num_foci = sum(foci_track>0);
    rand_track = zeros(iteration,size(foci_track,1));

    % Need to take into account num of foci that will fall together in order to
    % get an accurate simulated number of foci. Very roughly, probability
    % for spot #i to lie next to another spot is 2*i/(dna_length-i).

    est_foci = 0;
    dna_track_MC = dna_track.*(dna_track>0);
    proba = (num_foci)/sum(dna_track_MC);

    dna_pos = dip_image(dna_track)>0;
    dna_length = sum(dna_pos);
    cnt_foci = [];
    k = 1;
    while k<=iteration
        % Create a random number along track between 0 and 1 weighted by DAPI intensity value of pixel.
        rand_num = rand(size(foci_track));
        rand_track(k,:) = dna_track_MC*proba > rand_num;
        if sum(rand_track(k,:))>=3 % Make sure at least close to original num_foci, blurring will remove some...
            temp_gauss = gaussf(dip_image(rand_track(k,:)),sigma);
            temp_max = dip_localminima(-temp_gauss,[],1,max_depth*exp(-sigma),max_size,1);
            temp_max = and(temp_max,mask_track);
            if sum(temp_max)>2
                % Get center of consecutive max and set them as the only maximum
                ms1 = measure(label(temp_max,1,1,max_size),[],'center',[]);
                num_foci2 = size(ms1.Center,2);
                temp_max(:)=0;
                temp_max(round(ms1.center))=1;
                temp_max = label(temp_max,1,0,1)>0;
                cnt_foci = [cnt_foci num_foci2];
                rand_track(k,:) = double(temp_max);
                %temp_max_ind = find(rand_track(k,:)>0);
                Rdna_track(k) = mean(dna_track(rand_track(k,:)>0))/mean(dna_track(mask_track>0));
                Rgrad_track(k) = mean(track_grad(rand_track(k,:)>0))/mean(track_grad(mask_track>0));
                k = k+1;
            end
        end
    end
    % Plot to test overall if random foci reproduce dna pattern
%     plot(dna_track.*(foci_track>0),'ro')
%     hold;
%     plot(dna_track)
%     plot(sum(rand_track,1)*mean(dna_track)/mean(sum(rand_track,1)),'g')

    % fprintf('# of foci:%d  \t# of rand foci: %5.2f +/- %5.2f\n',num_foci,mean(cnt_foci),std(cnt_foci));
    Rdna = [mean(Rdna_track),sum(dna_track(mask_track).^2)/sum(dna_track(mask_track))^2*dna_length,std(Rdna_track)];
    Rgrad = [mean(Rgrad_track),std(Rgrad_track)];
    cnt_foci = [num_foci mean(cnt_foci)];
    fprintf('Rdna = %5.2f and Rgrad = %5.2f after randomization\n',Rdna(1),Rgrad(1));
end




