function [data,histo,dist,vel] = load_spot_track(filename,t_interval,min_tpoint)
% [data,histo,dist,vel] = load_spot_track(filename,t_interval,min_tpoint) 
% Input: filename with path of excel file to read spot tracking data from
% Bitplane
% Optional: t_interval: time interval in min.
%           min_tpoint: minimum # of time points to be used for max range
%           in histogram
%
% Loads output excel file generated by Bitplane spot track features. This
% implies that you copied on a separate file the Spot position worksheet in
% the following manner:
% File format example in excel:
% 		Data		
% Group	Time        Average of Position X	Average of Position Y	Average of Position Z
% Track 1	1       15.60000038             10                      5
%           2       15.39999962             10                      5
%           3       15.60000038             10                      5
%           4       15.39999962             10                      5
%           5       15.39999962             9.800000191             5
%           6       15.39999962             9.800000191             5
%           7       15.60000038             10                      5
%           8       15.39999962             10.19999981         	5
%           9       15.39999962             10.19999981         	5
%           10      15.19999981             10.19999981             5
%           11      15.39999962             10.39999962             5
% Track 1 Total		15.43636348             10.0545454              5
% Track 10	1       12.80000019             19                      5
%           2       12.80000019             19                      5
% etc...
%
%
% Output:
% - data 
%       The same as input file with two new columns (column 5 and 6).
%       time point | X | Y | Z | Distance^2 from original position | Velocity
%       You should copy back these columns into the excel file.
% - histo
%       Histogram of maximum distance range for each track over full time
%       course of track.
% - dist
%       Array of distance^2 from original position. For each time point,
%       a cell dist correspond. In that cell, is stored all the range
%       recorded by any tracks that had a value for that time point.
% - vel
%       Same as dist except it deals with the velocity data.
%
% Note: dist and vel are cell array with the number of cells equal the
% number of time points. Time point 1 though is empty, since to compute
% distances or velocity, one needs two time points.
%
%
% Sylvain Costes, LBNL, April 2007
%
a=importdata(filename);
data=a.data.Sheet1;
dtext = a.textdata.Sheet1;
hline = 2; % 2 headerlines in text file
t_pt = max(data(:,1)); % Number of time points
if ~(exist('t_interval'))
    t_interval = 1; % Time interval in min
    fprintf('Time interval assumed to be %d min\n',t_interval);
else
    fprintf('Time interval is %d min\n',t_interval);
end

if ~(exist('min_tpoint'))
    min_tpoint = 1; 
end

range_dist = 0:0.2:3.0; % Bin used for distances
range_vel = 0.00:0.05:1.00; % Bin used for velocities
% Look for row delimiting each track
track_array =[];
end_track = [];
for i=1+hline:length(dtext)
    if ~isempty(findstr(dtext{i,1},'Track'))
        if data(i-hline,1) >0 % Only true if we are at first value in track
            track_array = [track_array,i-hline];
        else % Mark end of track
            end_track = [end_track,i-hline-1];
        end
    end
end

ntrack = length(track_array);
dist{t_pt} = []; % This will set array of distance value for each time point
vel{t_pt} = [];
max_tpt = 0;

for i=1:ntrack
    temp_c = []; % cumulative distance to determine max and total length
    temp_vel = [];
    data(track_array(i),5) = NaN;
    data(track_array(i),6) = NaN;
    cnt=1;
    for j=track_array(i)+1:end_track(i)
        temp_dist = (data(j,2)-data(track_array(i),2))^2 + (data(j,3)-data(track_array(i),3))^2 + (data(j,4)-data(track_array(i),4))^2;
        data(j,6) = sqrt((data(j,2)-data(j-1,2))^2 + (data(j,3)-data(j-1,3))^2 + (data(j,4)-data(j-1,4))^2)/t_interval;
        temp_vel = [temp_vel data(j,6)];
        temp_c = [temp_c temp_dist];
        data(j,5) = temp_dist;
        dist{cnt} = [dist{cnt} temp_dist]; % Range is computed with relative time. i.e. t=0 is assumed for first data point.
                                           % This assumes also that each
                                           % time increment are the same...
        vel{data(j,1)} = [vel{data(j,1)} data(j,6)];
        cnt = cnt + 1;
    end
    if length(temp_c)>min_tpoint
        max_dist(i) = sqrt(max(temp_c));
    else
        max_dist(i) = NaN;
    end
    % Find the track that was monitor over the longest period of time
    if cnt-1>max_tpt
        max_tpt = cnt-1;
    end
end

for i=2:t_pt
    num_foci(i) = sum(vel{i}>0);
    avg_dist(i) = mean(dist{i});
    std_dist(i) = std(dist{i});
    avg_vel(i) = mean(vel{i});
    std_vel(i) = std(vel{i});
end

% Velocity information
figure; 
subplot(4,1,1); hold;
max_vel = 0;
for i=2:t_pt
    x_array = rand(length(vel{i}),1)/2.5 - 0.2; % Random number between -.2 and .2
    y_array = rand(length(vel{i}),1)/5 - 0.1; % Random number between -.1 and .1
    zero_array = zeros(length(vel{i}),1);
    plot((i-1)*t_interval+x_array,max(vel{i}+ y_array',zero_array'),'.');
    if max(vel{i})>max_vel
        max_vel = max(vel{i});
    end
end
errorbar((1:t_pt-1)*t_interval,avg_vel(2:t_pt),std_vel(2:t_pt),'-k')
xlabel('Time postIR (min)');
ylabel('foci velocity (um/min)');
ylim([0 max_vel])

% Distance information
subplot(4,1,2);  hold;
% Tried to have a contour bin plot but overlay is messed up. Kept it but
% commented it
% dist_array = zeros(length(range_dist),t_pt);
% x_array = repmat([0.5:t_pt-0.5]*t_interval,length(range_dist),1);
% y_array = repmat(range_dist',1,t_pt);
% for i=2:t_pt
% dist_array(:,i)=hist(dist{i},range_dist);
% end
% surf(x_array,y_array,dist_array);
for i=2:max_tpt
    x_array = rand(length(dist{i}),1)/2.5 - 0.2; % Random number between -.2 and .2
    y_array = rand(length(dist{i}),1)/5 - 0.1; % Random number between -.1 and .1
    zero_array = zeros(length(dist{i}),1);
    plot((i-1)*t_interval+x_array,max(dist{i}+ y_array',zero_array'),'.');
end
errorbar((1:max_tpt-1)*t_interval,avg_dist(2:max_tpt),std_dist(2:max_tpt),'-k')
xlabel('Time postIR (min)');
ylabel('Distance^2(um^2)');
ylim([0 max(max_dist)])

% Bining of range covered by foci
subplot(4,1,3); 
[h,hc] = hist(max_dist,range_dist);
bar(range_dist,h)
xlabel('Maximum range (um)');
ylabel('# of foci');

% Plot number of foci per time point
subplot(4,1,4);
plot(1:t_pt-1,num_foci(2:t_pt),'.');
xlabel('Time postIR (min)');
ylabel('Number of foci');
ylim([0 max(num_foci)*1.1]);

% Find small range versus large range
small_range_i = find(max_dist<0.1);
high_range_i = find(max_dist>1);
fprintf('Low range:\n');
dtext{track_array(small_range_i)+hline,1}
fprintf('High range:\n');
dtext{track_array(high_range_i)+hline,1}

% Display output to copy to excel
histo = [hc;h]';
% data(:,5:6)